# Generated by Django 4.2.3 on 2024-12-04 22:59

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('vagas', models.IntegerField(verbose_name=builtins.max)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
